// <auto-generated />
using System;
using LxGreg.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LxGreg.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190302120930_create")]
    partial class create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LxGreg.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ItemName");

                    b.Property<string>("ItemNumber");

                    b.Property<string>("ItemShortNumber");

                    b.Property<string>("Mark");

                    b.Property<string>("Model");

                    b.HasKey("Id");

                    b.ToTable("assets");
                });

            modelBuilder.Entity("LxGreg.Models.Manager", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("managers");
                });

            modelBuilder.Entity("LxGreg.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Mark");

                    b.Property<string>("OperaterId");

                    b.Property<DateTime>("OrderTime");

                    b.Property<int>("Quntity");

                    b.Property<string>("TakerId");

                    b.Property<int>("assetId");

                    b.Property<int>("storeId");

                    b.Property<int>("unitId");

                    b.HasKey("Id");

                    b.HasIndex("OperaterId");

                    b.HasIndex("TakerId");

                    b.HasIndex("assetId");

                    b.HasIndex("storeId");

                    b.HasIndex("unitId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("LxGreg.Models.Stock", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentQuntity");

                    b.Property<int>("assetId");

                    b.Property<int>("storeId");

                    b.Property<int>("unitId");

                    b.HasKey("id");

                    b.HasIndex("assetId");

                    b.HasIndex("storeId");

                    b.HasIndex("unitId");

                    b.ToTable("stocks");
                });

            modelBuilder.Entity("LxGreg.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StoreName");

                    b.HasKey("Id");

                    b.ToTable("stores");
                });

            modelBuilder.Entity("LxGreg.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UnitName");

                    b.HasKey("Id");

                    b.ToTable("units");
                });

            modelBuilder.Entity("LxGreg.Models.Order", b =>
                {
                    b.HasOne("LxGreg.Models.Manager", "Operater")
                        .WithMany()
                        .HasForeignKey("OperaterId");

                    b.HasOne("LxGreg.Models.Manager", "Taker")
                        .WithMany()
                        .HasForeignKey("TakerId");

                    b.HasOne("LxGreg.Models.Asset", "asset")
                        .WithMany("orders")
                        .HasForeignKey("assetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LxGreg.Models.Store", "store")
                        .WithMany("orders")
                        .HasForeignKey("storeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LxGreg.Models.Unit", "unit")
                        .WithMany("orders")
                        .HasForeignKey("unitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LxGreg.Models.Stock", b =>
                {
                    b.HasOne("LxGreg.Models.Asset", "asset")
                        .WithMany("stocks")
                        .HasForeignKey("assetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LxGreg.Models.Store", "store")
                        .WithMany("stocks")
                        .HasForeignKey("storeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LxGreg.Models.Unit", "unit")
                        .WithMany("stocks")
                        .HasForeignKey("unitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
